# Generated by Django 6.0 on 2026-01-02 21:45

import django.core.validators
import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=255, verbose_name='brand name')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('url', models.URLField(blank=True, default='', max_length=500, verbose_name='brand URL')),
                ('logo', models.URLField(blank=True, default='', max_length=500, verbose_name='logo URL')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'brand',
                'verbose_name_plural': 'brands',
                'indexes': [models.Index(fields=['slug', 'is_active'], name='products_br_slug_6e5060_idx')],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('icon', models.CharField(blank=True, default='', max_length=100, verbose_name='icon')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='display order')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['order', 'translations__name'],
                'indexes': [models.Index(fields=['slug', 'is_active'], name='products_ca_slug_269ba8_idx'), models.Index(fields=['order'], name='products_ca_order_ac6215_idx')],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('slug', models.SlugField(max_length=255, verbose_name='slug')),
                ('icon', models.CharField(blank=True, default='', max_length=100, verbose_name='icon')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.category', verbose_name='parent category')),
            ],
            options={
                'verbose_name': 'subcategory',
                'verbose_name_plural': 'subcategories',
                'ordering': ['order', 'translations__name'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('product_asin', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='product ASIN/ID')),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the title. Auto-generated if left blank.', max_length=550, unique=True, verbose_name='slug')),
                ('platform', models.CharField(choices=[('amazon', 'Amazon'), ('ebay', 'eBay'), ('aliexpress', 'AliExpress'), ('walmart', 'Walmart'), ('target', 'Target'), ('etsy', 'Etsy'), ('other', 'Other')], db_index=True, default='amazon', max_length=20, verbose_name='platform')),
                ('af_link', models.URLField(max_length=2000, verbose_name='affiliate link')),
                ('product_type', models.CharField(choices=[('electronics', 'Electronics'), ('clothing', 'Clothing'), ('home_garden', 'Home & Garden'), ('sports', 'Sports & Outdoors'), ('beauty', 'Beauty & Personal Care'), ('toys', 'Toys & Games'), ('books', 'Books'), ('automotive', 'Automotive'), ('grocery', 'Grocery'), ('health', 'Health & Household'), ('pet', 'Pet Supplies'), ('office', 'Office Products'), ('other', 'Other')], db_index=True, default='other', max_length=20, verbose_name='product type')),
                ('price_info', models.JSONField(blank=True, default=dict, help_text='Stores price, regular_price, cost_savings, discount_percent, savings_percent', verbose_name='price information')),
                ('features', models.JSONField(blank=True, default=list, help_text='List of feature objects with key and value', verbose_name='product features')),
                ('images', models.JSONField(blank=True, default=list, help_text='List of image objects with image, alt_text, is_featured, order', verbose_name='product images')),
                ('videos', models.JSONField(blank=True, default=list, help_text='List of video objects with video, title, is_featured, order', verbose_name='product videos')),
                ('meta', models.JSONField(blank=True, default=dict, help_text='SEO metadata: page_header, meta_description, meta_keywords, etc.', verbose_name='SEO meta data')),
                ('tags', models.TextField(blank=True, default='', help_text='Comma-separated list of tags', verbose_name='tags')),
                ('rating', models.DecimalField(blank=True, db_index=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='rating')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='is featured')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='view count')),
                ('click_count', models.PositiveIntegerField(default=0, verbose_name='click count')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.brand', verbose_name='brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='category')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.subcategory', verbose_name='subcategory')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['-created_at'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SubCategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=255, verbose_name='subcategory name')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='products.subcategory')),
            ],
            options={
                'verbose_name': 'subcategory Translation',
                'db_table': 'products_subcategory_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=255, verbose_name='category name')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='products.category')),
            ],
            options={
                'verbose_name': 'category Translation',
                'db_table': 'products_category_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=500, verbose_name='product title')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('shipping', models.CharField(blank=True, max_length=500, null=True, verbose_name='shipping info')),
                ('returns', models.CharField(blank=True, max_length=500, null=True, verbose_name='returns info')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='products.product')),
            ],
            options={
                'verbose_name': 'product Translation',
                'db_table': 'products_product_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['category', 'is_active'], name='products_su_categor_86a9be_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategory',
            index=models.Index(fields=['slug', 'category'], name='products_su_slug_182540_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('slug', 'category')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='products_pr_slug_3edc0c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['platform', 'is_active'], name='products_pr_platfor_e7d038_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_type', 'is_active'], name='products_pr_product_a5a1ea_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='products_pr_categor_50f5f1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand', 'is_active'], name='products_pr_brand_i_8f789e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'is_featured'], name='products_pr_is_acti_2fee29_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['rating', 'is_active'], name='products_pr_rating_da844c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at', 'is_active'], name='products_pr_created_97964d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subcategorytranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
